force-app/main/default/objects/Computer_2__c/Computer_2__c.object-meta.xml
<CustomObject>
    <label>Computer 2</label>
    <nameField>
        <label>Computer 2 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Computers2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Computer_2__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <label>Capacity</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Computer_2__c/fields/Hard_Disk_size__c.field-meta.xml
<CustomField>
    <fullName>Hard_Disk_size__c</fullName>
    <label>Hard Disk size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Computer_2__c/fields/Processor__c.field-meta.xml
<CustomField>
    <fullName>Processor__c</fullName>
    <label>Processor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ComputerTrigHandler.cls
public with sharing class ComputerTrigHandler {
    public static void updateCapacity(List<Computer_2__c> comps){
        for(Computer_2__c c: comps){
            if(c.RAM__c < 1 && c.Processor__c < 2 && c.Hard_Disk_size__c < 50){
                c.Capacity__c = 'Low Capacity';
            }
        }
    }

    public static void updateCapacity(List<Computer_2__c> comps, Map<id, Computer_2__c> compMap){
        for(Computer_2__c c: comps){

            Computer_2__c cOld = compMap.get(c.id);

            if(cOld.RAM__c != c.RAM__c || cOld.Processor__c != c.Processor__c || cOld.Hard_Disk_size__c != c.Hard_Disk_size__c){
                if(c.RAM__c < 1 && c.Processor__c < 2 && c.Hard_Disk_size__c < 50){
                    c.Capacity__c = 'Low Capacity';
                }
                else{
                    c.Capacity__c = '';
                }
            }
            
        }
    }
}