force-app/main/default/objects/Student__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <label>Teacher</label>
    <referenceTo>Teacher__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Teacher__c/Teacher__c.object-meta.xml
<CustomObject>
    <label>Teacher</label>
    <nameField>
        <label>Teacher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teachers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Teacher__c/fields/Department_Name__c.field-meta.xml
<CustomField>
    <fullName>Department_Name__c</fullName>
    <label>Department Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mechanical</fullName>
            </value>
            <value>
                <fullName>Computer</fullName>
            </value>
            <value>
                <fullName>Civil</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Teacher__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accounts</fullName>
            </value>
            <value>
                <fullName>Chemistry</fullName>
            </value>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Geography</fullName>
            </value>
            <value>
                <fullName>History</fullName>
            </value>
            <value>
                <fullName>Maths</fullName>
            </value>
            <value>
                <fullName>Physics</fullName>
            </value>
            <value>
                <fullName>Science</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TeacherTriggerHandler.cls
public with sharing class TeacherTriggerHandler {
    public static void operationAfterInsert(List<Teacher__c> newTeachers){
        TeacherUtility.firstTimeExecution = false;
        List<Student__c> students = new List<Student__c>();
        List<Teacher__c> teachers = new List<Teacher__c>();

        for(Teacher__c teacher: newTeachers){
            students.add(new Student__c(name = 'Student of'+ teacher.Subject__c, Teacher__c = teacher.id));
            Teacher__c t = new Teacher__c();
            if(teacher.Department_Name__c == 'Mechanical'){
                t.Subject__c = 'Physics';
            }
            else if(teacher.Department_Name__c == 'Computer'){
                t.Subject__c = 'Maths';
            }
            t.id = teacher.id;
            teachers.add(t);
        }

        System.debug(students);
        insert students;
        update teachers;
    }

    public static void operationBeforeUpdate(List<Teacher__c> updatedTeachers){
        System.debug('Inside before update');
    }

    public static void operationAfterUpdate(List<Teacher__c> updatedTeachers){
        System.debug('Inside after update');
    }
}