force-app/main/default/objects/Mobile__c/Mobile__c.object-meta.xml
<CustomObject>
    <label>Mobile</label>
    <nameField>
        <label>Mobile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mobiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mobile__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Samsung</fullName>
            </value>
            <value>
                <fullName>Apple</fullName>
            </value>
            <value>
                <fullName>Redmi</fullName>
            </value>
            <value>
                <fullName>Oneplus</fullName>
            </value>
            <value>
                <fullName>Realme</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MobileTrigHandler.cls
public with sharing class MobileTrigHandler {

    public static void calculateDiscound(List<Mobile__c> mobs){

        for(Mobile__c m: mobs){

            if(m.Brand__c == 'Apple' ){
                m.Price__c = m.Price__c * 0.80;
                m.Status__c = 'Congrats! You got 20% discount';
            }
            else if(m.Brand__c == 'Samsung'){
                m.Price__c = m.Price__c * 0.90;
                m.Status__c = 'Congrats! You got 10% discount';
            }
        }
    }

    public static void calculateDiscound(List<Mobile__c> mobs, Map<id,Mobile__c> mapMob){

        for(Mobile__c m: mobs){

            if(mapMob.get(m.id).Brand__c != m.Brand__c)
                if(m.Brand__c == 'Samsung'){
                    m.Price__c = m.Price__c * 0.95;
                    m.Status__c = 'Congrats! You got 5% discount';
                }
        }
    }

}