force-app/main/default/objects/Computer__c/Computer__c.object-meta.xml
<CustomObject>
    <label>Computer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Computers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Computer__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <label>Skill</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DotNet</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>Azure</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>AWS</fullName>
            </value>
            <value>
                <fullName>Java Script</fullName>
            </value>
            <value>
                <fullName>Angular JS</fullName>
            </value>
            <value>
                <fullName>React JS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MyBatch.cls
public class MyBatch implements Database.Batchable<Computer__c>{
    
    public static String query = 'select id,name,Skill__C from Computer__C';
	
    public list<Computer__C> start(Database.BatchableContext bc) {
        return [ select id,name from Computer__C ];
    }
	
	public void execute(Database.BatchableContext bc,list<Computer__C> comps){
	
	 list<Computer__C> upComps = new list<Computer__C>();
	 for(Computer__C c: comps){
	
		c.Skill__C = 'Salesforce '+c.name;
		upComps.add(c);
	 }
	 
	 update upComps;
	}
	
	public void finish(Database.BatchableContext bc){
	
	}
}